---
{{if and (index .Values "trusted-artifact-signer") (eq (index .Values "trusted-artifact-signer" "enabled") true)}}
{{ if (lookup "operators.coreos.com/v1alpha1" "Subscription" "openshift-operators" "rhtap-operator")}}
{{else}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    operators.coreos.com/rhtas-operator.openshift-operators: ""
  name: rhtas-operator
  namespace: openshift-operators
spec:
  channel: {{ index .Values "trusted-artifact-signer" "operator" "channel"}}
  installPlanApproval: Automatic
  name: rhtas-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhtas-operator.v1.0.0
{{ end}}
{{ end}}
