---
{{if and (index .Values "trusted-artifact-signer") (eq (index .Values "trusted-artifact-signer" "enabled") true)}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhtas-operator.openshift-operators: ""
  name: rhtas-operator
  namespace: openshift-operators
spec:
  channel: {{ index .Values "trusted-artifact-signer" "operator" "channel"}}
  installPlanApproval: Automatic
  name: rhtas-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhtas-operator.v0.0.2
{{ end}}
